# docker-compose.yml

services:

  numel-postgres:
    image: postgres:17-alpine
    container_name: numel-postgres
    environment:
      - POSTGRES_USER=${NUMEL_POSTGRES_USER}
      - POSTGRES_PASSWORD=${NUMEL_POSTGRES_PASSWORD}
      - POSTGRES_DB=${NUMEL_POSTGRES_DB}
      - POSTGRES_PORT=${NUMEL_POSTGRES_PORT}
      - NUMEL_POSTGRES_PATH=${NUMEL_POSTGRES_PATH}
    ports:
      - ${NUMEL_POSTGRES_PORT}:${NUMEL_POSTGRES_PORT}
    volumes:
      - ${NUMEL_POSTGRES_PATH}:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${NUMEL_POSTGRES_USER} -d ${NUMEL_POSTGRES_DB} -h localhost -p ${NUMEL_POSTGRES_PORT}"]
      interval: 5s
      timeout: 5s
      retries: 20
    restart: unless-stopped

  numel-app:
    build: .
    container_name: numel-app
    environment:
      - NUMEL_POSTGRES_USER=${NUMEL_POSTGRES_USER}
      - NUMEL_POSTGRES_PASSWORD=${NUMEL_POSTGRES_PASSWORD}
      - NUMEL_POSTGRES_DB=${NUMEL_POSTGRES_DB}
      - NUMEL_POSTGRES_PORT=${NUMEL_POSTGRES_PORT}
      - NUMEL_POSTGRES_PATH=${NUMEL_POSTGRES_PATH}
      - NUMEL_PORT_START=${NUMEL_PORT_START}
      - NUMEL_PORT_END=${NUMEL_PORT_END}
      - NUMEL_DEBUG_PORT=${NUMEL_DEBUG_PORT}
      - NUMEL_DEBUG=${NUMEL_DEBUG}
    ports:
      - ${NUMEL_PORT_START}-${NUMEL_PORT_END}:${NUMEL_PORT_START}-${NUMEL_PORT_END}
      - ${NUMEL_DEBUG_PORT}:${NUMEL_DEBUG_PORT}
    volumes:
      - .:/app
    command: ["sh", "./start.sh", "${NUMEL_DEBUG}", "${NUMEL_DEBUG_PORT}", "${NUMEL_PORT_START}"]
    restart: unless-stopped
    depends_on:
      numel-postgres:
        condition: service_healthy
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
