services:
  numel-app:
    build: .
    container_name: numel-app
    environment:
      - OLLAMA_HOST=http://host.docker.internal:11434
      - NUMEL_DEBUG=${NUMEL_DEBUG}
      - NUMEL_DEBUG_PORT=${NUMEL_DEBUG_PORT}
      - NUMEL_PORT_START=${NUMEL_PORT_START}
      - NUMEL_PORT_END=${NUMEL_PORT_END}
    ports:
      - ${NUMEL_PORT_START}-${NUMEL_PORT_END}:${NUMEL_PORT_START}-${NUMEL_PORT_END}
      - ${NUMEL_DEBUG_PORT}:${NUMEL_DEBUG_PORT}
    volumes:
      - .:/app
    command: tail -f /dev/null
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
